export const synonymMap: Record<string, string[]> = {
  // ~80 AI-writing common words mapped to natural alternatives
  "utilize": ["use", "apply"],
  "leverage": ["use", "draw on", "tap into", "make use of"],
  "implement": ["build", "set up", "put in place", "start"],
  "ensure": ["make sure", "confirm", "check that"],
  "facilitate": ["help", "ease", "make easier", "support"],
  "foster": ["encourage", "promote", "build"],
  "catalyst": ["spark", "driver", "trigger"],
  "paradigm": ["model", "setup", "pattern"],
  "synergy": ["teamwork", "collaboration", "combined effort"],
  "optimize": ["improve", "refine", "tune", "make better"],
  "streamline": ["simplify", "smooth out", "make easier"],
  "seamless": ["smooth", "flawless", "easy"],
  "robust": ["strong", "solid", "tough"],
  "comprehensive": ["full", "complete", "detailed"],
  "pivotal": ["key", "crucial", "main"],
  "paramount": ["top", "most important", "vital"],
  "imperative": ["crucial", "needed", "essential"],
  "innovative": ["new", "creative", "fresh"],
  "cutting-edge": ["new", "modern", "advanced"],
  "state-of-the-art": ["new", "advanced", "modern"],
  "subsequently": ["then", "later", "afterward"],
  "consequently": ["so", "as a result", "therefore"],
  "nevertheless": ["still", "even so", "anyway"],
  "furthermore": ["also", "plus", "what's more"],
  "moreover": ["also", "and", "besides"],
  "accordingly": ["so", "therefore", "as such"],
  "elucidate": ["explain", "clarify", "clear up"],
  "delineate": ["outline", "describe", "map out"],
  "underscore": ["highlight", "stress", "show"],
  "illuminate": ["explain", "show", "highlight"],
  "garner": ["gather", "collect", "get"],
  "mitigate": ["reduce", "lessen", "ease"],
  "ameliorate": ["improve", "make better", "help"],
  "exacerbate": ["worsen", "make worse"],
  "pertain": ["relate", "apply", "concern"],
  "encompass": ["include", "cover", "contain"],
  "manifest": ["show", "display", "appear"],
  "embark": ["start", "begin", "set out"],
  "endeavor": ["try", "effort", "attempt"],
  "holistic": ["full", "overall", "complete"],
  "intrinsic": ["core", "basic", "built-in"],
  "extrinsic": ["outside", "external"],
  "prevalent": ["common", "widespread", "usual"],
  "ubiquitous": ["everywhere", "all over", "common"],
  "profound": ["deep", "major", "intense"],
  "myriad": ["many", "lots of", "various"],
  "plethora": ["lot", "bunch", "wealth"],
  "abundance": ["lot", "plenty", "wealth"],
  "commence": ["start", "begin", "kick off"],
  "terminate": ["end", "stop", "finish"],
  "ascertain": ["find out", "check", "determine"],
  "corroborate": ["confirm", "back up", "support"],
  "substantiate": ["prove", "back up", "verify"],
  "validate": ["check", "prove", "confirm"],
  "augment": ["add to", "increase", "grow"],
  "diminish": ["reduce", "lower", "drop"],
  "fluctuate": ["change", "vary", "shift"],
  "pervasive": ["widespread", "common", "everywhere"],
  "salient": ["main", "key", "standout"],
  "tangible": ["real", "solid", "clear"],
  "viable": ["workable", "doable", "good"],
  "feasible": ["doable", "possible", "workable"],
  "lucrative": ["profitable", "rewarding", "paying"],
  "meticulous": ["careful", "detailed", "thorough"],
  "pragmatic": ["practical", "sensible", "realistic"],
  "superfluous": ["extra", "unneeded", "excess"],
  "vital": ["key", "crucial", "needed"],
  "crucial": ["key", "vital", "must-have"],
  "essential": ["key", "needed", "basic"],
  "fundamental": ["basic", "core", "key"],
  "integral": ["key", "core", "vital"],
  "indispensable": ["vital", "crucial", "needed"],
  "prominent": ["main", "well-known", "standout"],
  "eminent": ["top", "famous", "notable"],
  "notable": ["key", "important", "standout"],
  "significant": ["major", "key", "important"],
  "substantial": ["large", "solid", "major"],
  "considerable": ["large", "a lot", "significant"],
  "copious": ["lots of", "many", "plenty"],
  "ample": ["plenty", "enough", "lots of"]
};
